### ISSUE TITLE
닉네임 등록 및 수정

### ISSUE THREAD

**Issue by somin-jeong** [SWYP-InNOut/InNOut-Backend#50]
## 상세 내용
accessToken 받아서 nickname이 등록된 회원이면 nickname update
nickname이 아직 등록되어 있지 않은 회원이면 nickname insert

## ToDo
- [ ] nickname이 등록되어 있는지 확인
- [ ] db에 nickname update
- [ ] db에 nickname insert
